/* ============================================================
   build.mjs  ::  static site build for thebharath.co
   Transforms the JSX sources (which rely on global React /
   ReactDOM) into a single minified bundle, and minifies the
   stylesheet, emitting deploy-ready artifacts to the repo root.
   The browser never ships an in-page transpiler. No framework,
   fully static, GitHub Pages friendly (served from root).

   Asset filenames are content-hashed (assets/bundle.<hash>.js,
   assets/gta.<hash>.css) and index.html is rewritten to point at
   them. That is what makes the year-long immutable Cache-Control
   in vercel.json correct: a changed file gets a new URL, so a
   returning visitor can never be served a stale bundle behind a
   cache entry it was told never to revalidate.
   ============================================================ */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import {
  readFile, writeFile, mkdir, copyFile, access, readdir, rm,
} from "node:fs/promises";

const ASSET_DIR = "assets";
const HASH_LEN = 10;
const hashOf = (s) => createHash("sha256").update(s).digest("hex").slice(0, HASH_LEN);

// Matches a reference in whatever form it currently has: the original
// unhashed name, or a hashed one from a previous build. That keeps the
// rewrite idempotent, so index.html can stay both the committed source
// and the served output without drifting.
const REF = {
  js: /(?:assets\/)?bundle(?:\.[0-9a-f]{6,})?\.js/g,
  css: /(?:assets\/)?gta(?:\.[0-9a-f]{6,})?\.css/g,
};

// Static files (next to index.html) copied into dist/, optionally under a
// cleaner served name ({ from, to }). A missing source is skipped, not an
// error, so the build stays green even before the asset is added.
const STATIC_ASSETS = [
  { from: "Bharath_Kumar_Rajesh_Master_Resume.pdf", to: "resume.pdf" },
];

// Plain JS sources are concatenated verbatim (already valid).
const JS_SOURCES = ["src/content.js"];

// JSX sources, in the original prototype's <script> load order.
// They share a single global lexical scope (e.g. `const {useState}=React`
// declared in gta_components is read bare in the other files), so they
// must NOT be wrapped per-file. esbuild's transform mode keeps top-level
// names, so plain concatenation preserves that contract.
const JSX_SOURCES = [
  "src/gta_components.jsx",
  "src/gta_hero.jsx",
  "src/gta_skills_exp.jsx",
  "src/gta_projects.jsx",
  "src/gta_trophy_contact.jsx",
  "src/gta_app.jsx",
];

async function transformJsx(file) {
  const result = await build({
    entryPoints: [file],
    write: false,
    bundle: false,
    minify: true,
    jsx: "transform",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    loader: { ".jsx": "jsx" },
  });
  return result.outputFiles[0].text;
}

/* Delete hashed artifacts from earlier builds so the repo (and dist/) hold
   exactly one bundle and one stylesheet, never an accumulating pile. */
async function pruneStaleAssets(dir, keep) {
  let entries;
  try {
    entries = await readdir(dir);
  } catch {
    return []; // directory does not exist yet
  }
  const stale = entries.filter(
    (f) => /^(bundle|gta)\.[0-9a-f]{6,}\.(js|css)$/.test(f) && !keep.includes(f)
  );
  for (const f of stale) await rm(`${dir}/${f}`);
  return stale;
}

/* The pre-fingerprint artifacts. They were served under a year-long
   immutable Cache-Control at stable URLs, which is the bug this build
   fixes, so make sure a build never leaves one lying around to be served
   again. Safe to drop once index.html no longer references them. */
async function removeLegacyAssets(dir) {
  const gone = [];
  for (const f of ["bundle.js", "gta.css"]) {
    const path = dir ? `${dir}/${f}` : f;
    try {
      await rm(path);
      gone.push(path);
    } catch {
      /* already absent */
    }
  }
  return gone;
}

async function run() {
  let bundle =
    "/* generated by build.mjs from src/ - do not edit directly */\n";
  for (const f of JS_SOURCES) bundle += (await readFile(f, "utf8")) + "\n";
  for (const f of JSX_SOURCES) bundle += (await transformJsx(f)) + "\n";

  const cssOut = await build({
    entryPoints: ["src/gta.css"],
    write: false,
    minify: true,
    loader: { ".css": "css" },
  });
  const css = cssOut.outputFiles[0].text;

  const jsFile = `bundle.${hashOf(bundle)}.js`;
  const cssFile = `gta.${hashOf(css)}.css`;
  const jsHref = `${ASSET_DIR}/${jsFile}`;
  const cssHref = `${ASSET_DIR}/${cssFile}`;

  // index.html is the served page and is rewritten in place, the same way
  // bundle and stylesheet artifacts are already committed at the root.
  const html = (await readFile("index.html", "utf8"))
    .replace(REF.js, jsHref)
    .replace(REF.css, cssHref);

  await mkdir(ASSET_DIR, { recursive: true });
  await writeFile(jsHref, bundle);
  await writeFile(cssHref, css);
  await writeFile("index.html", html);
  const prunedRoot = [
    ...(await pruneStaleAssets(ASSET_DIR, [jsFile, cssFile])),
    ...(await removeLegacyAssets("")),
  ];

  // Self-contained output dir for Vercel (outputDirectory: "dist"), so the
  // deploy never serves node_modules or source. GitHub Pages uses the root
  // copies above. Both stay in sync from this one build.
  await mkdir(`dist/${ASSET_DIR}`, { recursive: true });
  await writeFile("dist/index.html", html);
  await writeFile(`dist/${jsHref}`, bundle);
  await writeFile(`dist/${cssHref}`, css);
  await pruneStaleAssets(`dist/${ASSET_DIR}`, [jsFile, cssFile]);
  await removeLegacyAssets("dist");

  const copiedAssets = [];
  for (const { from, to } of STATIC_ASSETS) {
    try {
      await access(from);
    } catch {
      continue; // not present yet, skip without failing the build
    }
    await copyFile(from, `dist/${to}`);
    copiedAssets.push(to);
  }

  const extra = copiedAssets.length ? `, ${copiedAssets.join(", ")}` : "";
  const pruned = prunedRoot.length ? `\nPruned: ${prunedRoot.join(", ")}` : "";
  console.log(`Built: ${cssHref}, ${jsHref}${extra} (root + dist/)${pruned}`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
